from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from beacon.core.constants import (
    BATTERY_INITIAL,
    C_MAX,
    DELTA_COL,
    DELTA_MOVE,
    DELTA_TIME,
    T_MAP,
)
from beacon.core.models import OnlineSurpResult
from beacon.core.scene_configs import assign_semantic_cost


# ── data class ────────────────────────────────────────────────────────────────

@dataclass
class RunMetrics:
    # ── identity ───────────────────────────────────────────────────────────
    config:            str    # "S-U" | "S-M" | "M-U" | "M-M" | "D-U" | "D-M"
    algorithm:         str    # "BEACON" | "Bug1" | "Bug2" | "Greedy"
    trial:             int
    seed:              int
    family:            str

    # ── navigation efficiency ──────────────────────────────────────────────
    success:           bool
    step_count:        int
    path_length_m:     float
    straight_line_m:   float
    arrival_time_s:    float   # simulated seconds = step_count × T_MAP
    path_efficiency:   float   # straight_line / path_length  (≤ 1)

    # ── resource ───────────────────────────────────────────────────────────
    battery_consumed:  float   # units expended
    battery_remaining: float   # < 0 means battery died

    # ── contact quality ────────────────────────────────────────────────────
    push_count:        int
    contact_cost:      float   # Σ c(Ok) for all pushes
    dangerous_contacts: int    # pushes where c(Ok) > C_MAX

    # ── timing ─────────────────────────────────────────────────────────────
    planning_time_ms:  float   # mean wall-clock ms per control step

    # ── environment context ────────────────────────────────────────────────
    obstacle_count:    int
    density:           str
    fragility_profile: str


# ── helper: semantic cost lookup ──────────────────────────────────────────────

def _obstacle_semantic_cost(obstacle: dict) -> int:
    """Return c(Ok) for one obstacle, using stored value or falling back to
    a class-based estimate when the scene was generated without it."""
    if "semantic_cost" in obstacle:
        return int(obstacle["semantic_cost"])
    # Fallback for scenes generated by the old generator
    return assign_semantic_cost(obstacle.get("true_class", "movable"))


# ── battery model ─────────────────────────────────────────────────────────────

def _compute_battery(path: list, push_count: int) -> tuple[float, float]:
    """Return (battery_consumed, battery_remaining) using the paper's model:

        ΔB = δ_move × d + δ_time × Δt + δ_col × N_pushes
    """
    path_arr    = np.array(path)
    path_length = float(np.sum(np.linalg.norm(np.diff(path_arr, axis=0), axis=1)))
    n_steps     = max(len(path) - 1, 0)

    consumed = (
        DELTA_MOVE * path_length
        + DELTA_TIME * n_steps
        + DELTA_COL  * push_count
    )
    remaining = BATTERY_INITIAL - consumed
    return consumed, remaining


# ── contact parsing ───────────────────────────────────────────────────────────

def _parse_contacts(contact_log: list[str], obstacles: list[dict]) -> tuple[float, int]:
    """Return (total_contact_cost, dangerous_contact_count) from the contact log.

    Each log entry looks like:
        "... pushed obstacle 3 by 0.12 ..."
    We look up c(Ok) for the referenced obstacle id.
    """
    obs_by_id = {obs.get("id"): obs for obs in obstacles}
    total_cost   = 0.0
    n_dangerous  = 0

    for entry in contact_log:
        try:
            obs_id = int(entry.split("obstacle ")[1].split(" ")[0])
            obs    = obs_by_id.get(obs_id)
            if obs is None:
                continue
            c = _obstacle_semantic_cost(obs)
            total_cost  += c
            if c > C_MAX:
                n_dangerous += 1
        except (ValueError, IndexError):
            pass

    return total_cost, n_dangerous


# ── public API ────────────────────────────────────────────────────────────────

def compute_metrics(
    result:           OnlineSurpResult,
    algorithm:        str   = "BEACON",
    config:           str   = "unknown",
    trial:            int   = 0,
    planning_time_s:  float = 0.0,
) -> RunMetrics:
    """Compute one ``RunMetrics`` row from a completed simulation result."""

    path      = np.array(result.path)
    scene     = result.scene
    obstacles = scene["obstacles"]

    # navigation
    step_count   = max(len(result.frames) - 1, 0)
    path_length  = float(np.sum(np.linalg.norm(np.diff(path, axis=0), axis=1)))
    start        = np.array(scene["start"][:2])
    goal         = np.array(scene["goal"][:2])
    straight     = float(np.linalg.norm(goal - start))
    efficiency   = straight / max(path_length, 1e-6)
    arrival_time = step_count * T_MAP

    # battery
    push_count              = len(result.contact_log)
    battery_consumed, battery_remaining = _compute_battery(result.path, push_count)

    # contact quality
    contact_cost, dangerous = _parse_contacts(result.contact_log, obstacles)

    # timing
    planning_ms = (planning_time_s / max(step_count, 1)) * 1000.0

    # environment context
    obs_count         = len(obstacles)
    density           = scene.get("density",           "unknown")
    fragility_profile = scene.get("fragility_profile", "unknown")

    return RunMetrics(
        config            = config,
        algorithm         = algorithm,
        trial             = trial,
        seed              = int(result.seed),
        family            = result.family,
        success           = result.success,
        step_count        = step_count,
        path_length_m     = path_length,
        straight_line_m   = straight,
        arrival_time_s    = arrival_time,
        path_efficiency   = efficiency,
        battery_consumed  = battery_consumed,
        battery_remaining = battery_remaining,
        push_count        = push_count,
        contact_cost      = contact_cost,
        dangerous_contacts = dangerous,
        planning_time_ms  = planning_ms,
        obstacle_count    = obs_count,
        density           = density,
        fragility_profile = fragility_profile,
    )
